
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.


[[constraint]]
  name = "k8s.io/apimachinery"
  version="kubernetes-1.10.3"

[[constraint]]
  name = "k8s.io/api"
  version="kubernetes-1.10.3"


[[constraint]]
  name = "k8s.io/client-go"
  version = "v7.0.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"
